import OpenAI from "openai";
import type {
  AIProvider,
  AIProviderConfig,
  AIProviderResult,
  AIProviderType,
  AIGenerateOptions,
} from "../types";
import { createProviderInterface } from "../provider";
import { sanitizePrompt } from "./deterministic";

let openaiInstance: OpenAI | null = null;

function getOpenAIClient(config: AIProviderConfig): OpenAI {
  if (!openaiInstance) {
    if (!config.apiKey) {
      throw new Error("OPENAI_API_KEY is required for OpenAI provider");
    }
    openaiInstance = new OpenAI({
      apiKey: config.apiKey,
      organization: config.organizationId,
    });
  }
  return openaiInstance;
}

export function createOpenAIProvider(
  config: AIProviderConfig
): AIProvider {
  const client = getOpenAIClient(config);

  const provider = createProviderInterface(
    "OpenAI Provider",
    "openai",
    config,
    async function generateStructured<T>(
      prompt: string,
      schema: unknown,
      options?: AIGenerateOptions
    ): Promise<AIProviderResult<T>> {
      const startTime = Date.now();
      const errors: string[] = [];
      const safePrompt = sanitizePrompt(prompt);

      try {
        const completion = await client.chat.completions.create({
          model: config.model || "gpt-4o-mini",
          messages: [
            {
              role: "system",
              content:
                "You are a structured AI assistant for GrowthOS. " +
                "Always return structured JSON proposals. " +
                "NEVER directly execute payments, refunds, or Razorpay operations. " +
                "Only generate structured proposals. " +
                "Never expose chain-of-thought. Only provide a short reasoning summary.",
            },
            { role: "user", content: safePrompt },
          ],
          temperature: options?.temperature ?? config.temperature ?? 0.7,
          max_tokens: options?.maxTokens ?? config.maxTokens ?? 2048,
        });

        const content = completion.choices[0]?.message?.content;
        if (!content) {
          errors.push("OpenAI returned empty response");
          return {
            success: false,
            data: {} as T,
            confidence: { level: "LOW", score: 0, reasoning: "Empty response from OpenAI" },
            reasoning: {
              sources: [],
              methodology: "openai-llm",
              dataPoints: 0,
              confidenceScore: 0,
              reasoningSummary: "Empty response from OpenAI",
            },
            provider: "openai",
            durationMs: Date.now() - startTime,
            errors,
          };
        }

        let parsed: unknown;
        try {
          parsed = JSON.parse(content);
        } catch {
          errors.push("OpenAI response was not valid JSON");
          return {
            success: false,
            data: {} as T,
            confidence: { level: "LOW", score: 0, reasoning: "Invalid JSON from OpenAI" },
            reasoning: {
              sources: ["openai"],
              methodology: "openai-llm",
              dataPoints: 1,
              confidenceScore: 0,
              reasoningSummary: "OpenAI returned non-JSON response",
            },
            provider: "openai",
            durationMs: Date.now() - startTime,
            errors,
          };
        }

        const compliance = validateStructuredAIOutput(parsed);
        if (!compliance.compliant) {
          errors.push(...compliance.errors);
        }

        return {
          success: errors.length === 0,
          data: parsed as T,
          confidence: {
            level: compliance.compliant ? "HIGH" : "MEDIUM",
            score: compliance.compliant ? 95 : 50,
            reasoning: compliance.compliant
              ? "OpenAI generated compliant structured output"
              : "OpenAI output had validation issues",
          },
          reasoning: {
            sources: ["openai"],
            methodology: "openai-llm",
            dataPoints: 1,
            confidenceScore: compliance.compliant ? 95 : 50,
            reasoningSummary: compliance.compliant
              ? "Generated by OpenAI with structured schema compliance"
              : "Generated by OpenAI with validation warnings",
          },
          provider: "openai",
          durationMs: Date.now() - startTime,
          errors,
        };
      } catch (error: any) {
        const message = error?.message || "OpenAI API error";
        errors.push(message);
        return {
          success: false,
          data: {} as T,
          confidence: { level: "LOW", score: 0, reasoning: message },
          reasoning: {
            sources: [],
            methodology: "openai-llm",
            dataPoints: 0,
            confidenceScore: 0,
            reasoningSummary: `OpenAI API error: ${message}`,
          },
          provider: "openai",
          durationMs: Date.now() - startTime,
          errors,
        };
      }
    },
    function validateOutput<T>(output: unknown, schema: unknown): boolean {
      if (output === null || output === undefined) return false;
      const compliance = validateStructuredAIOutput(output);
      return compliance.compliant;
    }
  );

  return provider;
}

export function validateStructuredAIOutput(output: unknown): { compliant: boolean; errors: string[] } {
  const errors: string[] = [];

  if (output === null || output === undefined) {
    errors.push("Output is null or undefined");
    return { compliant: false, errors };
  }

  if (typeof output !== "object") {
    errors.push("Output is not an object");
    return { compliant: false, errors };
  }

  const obj = output as Record<string, unknown>;

  if (!obj.intent || typeof obj.intent !== "string") {
    errors.push("Missing or invalid intent field");
  }
  if (!obj.action || typeof obj.action !== "string") {
    errors.push("Missing or invalid action field");
  }
  if (typeof obj.confidence !== "number" || obj.confidence < 0 || obj.confidence > 100) {
    errors.push("Confidence must be a number between 0 and 100");
  }
  if (typeof obj.requiresApproval !== "boolean") {
    errors.push("requiresApproval must be a boolean");
  }
  if (!obj.reasoningSummary || typeof obj.reasoningSummary !== "string") {
    errors.push("Missing or invalid reasoningSummary");
  }

  return { compliant: errors.length === 0, errors };
}

export function resetOpenAIClient(): void {
  openaiInstance = null;
}
